// ============================================================
// Admin Generator - مولد لوحة التحكم
// ============================================================
// Automatically generates CRUD (Create, Read, Update, Delete)
// controllers, views, and routes for a model.
//
// يولد تلقائياً CRUD controllers و views و routes للنموذج.
// ============================================================

use serde::{Serialize, Deserialize};

/// Field configuration for scaffolding
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScaffoldField {
    pub name: String,
    pub field_type: FieldType,
    pub label: String,
    pub required: bool,
    pub searchable: bool,
    pub sortable: bool,
    pub in_list: bool,  // Show in list view
    pub in_form: bool,  // Show in create/edit form
    pub in_show: bool,  // Show in detail view
    pub validation: Vec<ValidationRule>,
    pub default_value: Option<serde_json::Value>,
    pub options: Option<Vec<(String, String)>>,  // For select fields
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum FieldType {
    String,
    Text,
    Integer,
    Float,
    Boolean,
    Date,
    DateTime,
    Email,
    Url,
    Password,
    Select,
    Textarea,
    File,
    Image,
    Json,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ValidationRule {
    pub rule: String,  // required, min:3, max:255, email, unique, etc.
    pub message: String,
}

/// Scaffold configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScaffoldConfig {
    pub model_name: String,
    pub table_name: String,
    pub fields: Vec<ScaffoldField>,
    pub per_page: u32,
    pub searchable: bool,
    pub sortable: bool,
    pub export_csv: bool,
    pub soft_delete: bool,
}

impl Default for ScaffoldConfig {
    fn default() -> Self {
        Self {
            model_name: "Model".to_string(),
            table_name: "models".to_string(),
            fields: vec![],
            per_page: 15,
            searchable: true,
            sortable: true,
            export_csv: false,
            soft_delete: false,
        }
    }
}

/// Admin generator
pub struct AdminGenerator {
    config: ScaffoldConfig,
}

impl AdminGenerator {
    pub fn new(config: ScaffoldConfig) -> Self {
        Self { config }
    }
    
    /// Generate the controller code
    pub fn generate_controller(&self) -> String {
        let model = &self.config.model_name;
        let model_lower = model.to_lowercase();
        
        format!(
            r#"// ============================================================
// {} Controller - Generated by Noor Admin Generator
// متحكم {} - مولد بواسطة مولد لوحة التحكم
// ============================================================

use noor::*;
use noor::core::http::{{Request, Response, StatusCode}};
use noor::core::pagination::PaginationParams;

/// {} controller
pub struct {}Controller;

impl {}Controller {{
    /// List {}s with pagination
    /// عرض قائمة {}s مع التصفح
    pub fn index(req: Request) -> NoorResult<Response> {{
        let params = PaginationParams::from_query(&req.query_params);
        
        // TODO: Fetch from database
        // let items = {}::paginate(params.page, params.per_page);
        
        Ok(Response::ok().json(&serde_json::json!({{
            "data": [],
            "meta": {{
                "current_page": params.page,
                "per_page": params.per_page,
                "total": 0,
            }}
        }}))?))
    }}
    
    /// Show a single {}
    pub fn show(req: Request) -> NoorResult<Response> {{
        let id = req.param("id").unwrap_or("0");
        
        // TODO: Fetch from database
        // let item = {}::find(id)?;
        
        Ok(Response::ok().json(&serde_json::json!({{
            "data": {{"id": id}}
        }}))?))
    }}
    
    /// Create a new {}
    pub fn store(req: Request) -> NoorResult<Response> {{
        let body: serde_json::Value = req.json()?;
        
        // Validate input
{}
        
        // TODO: Create in database
        // let item = {}::create(body)?;
        
        Ok(Response::new(StatusCode::CREATED).json(&serde_json::json!({{
            "message": "{} created successfully",
            "data": body,
        }}))?))
    }}
    
    /// Update an existing {}
    pub fn update(req: Request) -> NoorResult<Response> {{
        let id = req.param("id").unwrap_or("0");
        let body: serde_json::Value = req.json()?;
        
        // TODO: Update in database
        // let item = {}::update(id, body)?;
        
        Ok(Response::ok().json(&serde_json::json!({{
            "message": "{} updated successfully",
            "id": id,
            "data": body,
        }}))?))
    }}
    
    /// Delete a {}
    pub fn destroy(req: Request) -> NoorResult<Response> {{
        let id = req.param("id").unwrap_or("0");
        
        // TODO: Delete from database
        // {}::delete(id)?;
        
        Ok(Response::new(StatusCode::NO_CONTENT))
    }}
}}

/// Register {} routes
pub fn register_routes(router: &mut Router) {{
    router.get("/admin/{}", {}Controller::index);
    router.post("/admin/{}", {}Controller::store);
    router.get("/admin/{{}}", {}Controller::show);
    router.put("/admin/{{}}", {}Controller::update);
    router.delete("/admin/{{}}", {}Controller::destroy);
}}
"#,
            model, model,
            model, model, model,
            model_lower, model_lower,
            model,
            model,
            self.generate_validation_code(),
            model, model,
            model,
            model, model,
            model,
            model, model,
            model,
            model_lower, model,
            model_lower, model,
            model_lower, model,
            model_lower, model,
        )
    }
    
    /// Generate validation code
    fn generate_validation_code(&self) -> String {
        let mut validations = Vec::new();
        
        for field in &self.config.fields {
            if field.required {
                validations.push(format!(
                    r#"        Validator::required(
            body.get("{}").and_then(|v| v.as_str()).unwrap_or(""),
            "{}"
        )?;"#,
                    field.name, field.name
                ));
            }
            
            for rule in &field.validation {
                match rule.rule.as_str() {
                    "email" => {
                        validations.push(format!(
                            r#"        if let Some(email) = body.get("{}").and_then(|v| v.as_str()) {{
            if !email.is_empty() {{
                Validator::email(email, "{}")?;
            }}
        }}"#,
                            field.name, field.name
                        ));
                    }
                    "min" => {
                        if let Some(min) = rule.rule.strip_prefix("min:") {
                            validations.push(format!(
                                r#"        if let Some(val) = body.get("{}").and_then(|v| v.as_str()) {{
            if !val.is_empty() {{
                Validator::min_length(val, "{}", {})?;
            }}
        }}"#,
                                field.name, field.name, min
                            ));
                        }
                    }
                    "max" => {
                        if let Some(max) = rule.rule.strip_prefix("max:") {
                            validations.push(format!(
                                r#"        if let Some(val) = body.get("{}").and_then(|v| v.as_str()) {{
            if !val.is_empty() {{
                Validator::max_length(val, "{}", {})?;
            }}
        }}"#,
                                field.name, field.name, max
                            ));
                        }
                    }
                    _ => {}
                }
            }
        }
        
        validations.join("\n")
    }
    
    /// Generate the HTML list view
    pub fn generate_list_view(&self) -> String {
        let model = &self.config.model_name;
        let model_lower = model.to_lowercase();
        
        let headers: Vec<String> = self.config.fields
            .iter()
            .filter(|f| f.in_list)
            .map(|f| format!("<th>{}</th>", f.label))
            .collect();
        
        let cells: Vec<String> = self.config.fields
            .iter()
            .filter(|f| f.in_list)
            .map(|f| format!("<td>{{{{row.{}}}}}</td>", f.name))
            .collect();
        
        format!(
            r#"{{{{#extend "layouts/app"}}}}
{{{{#content "content"}}}}
<div class="container">
    <div class="flex-between mb-2">
        <h1>{}s</h1>
        <a href="/admin/{}/new" class="btn btn-success">+ New {}</a>
    </div>
    
    <div class="card">
        <table class="table">
            <thead>
                <tr>
                    {}
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {{{{#each items}}}}
                <tr>
                    {}
                    <td>
                        <a href="/admin/{}/{{{{this.id}}}}" class="btn btn-primary btn-sm">View</a>
                        <a href="/admin/{}/{{{{this.id}}}}/edit" class="btn btn-secondary btn-sm">Edit</a>
                        <a href="/admin/{}/{{{{this.id}}}}/delete" class="btn btn-danger btn-sm" data-confirm="Delete?">Delete</a>
                    </td>
                </tr>
                {{{{/each}}}}
            </tbody>
        </table>
        
        {{{{#if pagination}}}}
        <div class="text-center mt-2">
            {{{{#if pagination.prev}}}}<a href="?page={{{{pagination.prev}}}}" class="btn btn-secondary btn-sm">Previous</a>{{{{/if}}}}
            <span>Page {{{{pagination.current}}}} of {{{{pagination.last}}}}</span>
            {{{{#if pagination.next}}}}<a href="?page={{{{pagination.next}}}}" class="btn btn-secondary btn-sm">Next</a>{{{{/if}}}}
        </div>
        {{{{/if}}}}
    </div>
</div>
{{{{/content}}}}
{{{{/extend}}}}"#,
            model,
            model_lower, model,
            headers.join("\n                    "),
            cells.join("\n                    "),
            model_lower,
            model_lower,
            model_lower,
        )
    }
    
    /// Generate the HTML form view
    pub fn generate_form_view(&self) -> String {
        let model = &self.config.model_name;
        let model_lower = model.to_lowercase();
        
        let form_fields: Vec<String> = self.config.fields
            .iter()
            .filter(|f| f.in_form)
            .map(|f| {
                let input_type = match f.field_type {
                    FieldType::Email => "email",
                    FieldType::Password => "password",
                    FieldType::Integer | FieldType::Float => "number",
                    FieldType::Date => "date",
                    FieldType::DateTime => "datetime-local",
                    FieldType::Url => "url",
                    FieldType::File | FieldType::Image => "file",
                    _ => "text",
                };
                
                let required = if f.required { "required" } else { "" };
                
                match f.field_type {
                    FieldType::Textarea | FieldType::Text => {
                        format!(
                            r#"            <div class="form-group">
                <label for="{}">{}</label>
                <textarea id="{}" name="{}" {} placeholder="Enter {}">{{{{values.{}}}}}</textarea>
            </div>"#,
                            f.name, f.label,
                            f.name, f.name, required, f.label, f.name
                        )
                    }
                    FieldType::Select => {
                        let options = f.options.as_ref().map(|opts| {
                            opts.iter().map(|(value, label)| {
                                format!(r#"<option value="{}">{}</option>"#, value, label)
                            }).collect::<Vec<_>>().join("\n                        ")
                        }).unwrap_or_default();
                        
                        format!(
                            r#"            <div class="form-group">
                <label for="{}">{}</label>
                <select id="{}" name="{}" {}>
                        {}
                </select>
            </div>"#,
                            f.name, f.label,
                            f.name, f.name, required,
                            options
                        )
                    }
                    FieldType::Boolean => {
                        format!(
                            r#"            <div class="form-group">
                <label>
                    <input type="checkbox" id="{}" name="{}" {{{{#if values.{}}}}}checked{{{{/if}}}}>
                    {}
                </label>
            </div>"#,
                            f.name, f.name, f.name, f.label
                        )
                    }
                    _ => {
                        format!(
                            r#"            <div class="form-group">
                <label for="{}">{}</label>
                <input type="{}" id="{}" name="{}" value="{{{{values.{}}}}}" {} placeholder="Enter {}">
            </div>"#,
                            f.name, f.label,
                            input_type,
                            f.name, f.name, f.name, required, f.label
                        )
                    }
                }
            })
            .collect();
        
        format!(
            r#"{{{{#extend "layouts/app"}}}}
{{{{#content "content"}}}}
<div class="container-narrow">
    <div class="card">
        <h1>{{{{#if edit}}}}Edit {}{{{{else}}}}New {}{{{{/if}}}}</h1>
        
        <form method="POST" action="{{{{#if edit}}}}/admin/{}/{{{{values.id}}}}{{{{else}}}}/admin/{}{{{{/if}}}}" data-validate>
{}
            <div class="flex gap-2 mt-2">
                <button type="submit" class="btn btn-primary">Save</button>
                <a href="/admin/{}" class="btn btn-secondary">Cancel</a>
            </div>
        </form>
    </div>
</div>
{{{{/content}}}}
{{{{/extend}}}}"#,
            model, model,
            model_lower, model_lower,
            form_fields.join("\n"),
            model_lower,
        )
    }
    
    /// Generate the show view
    pub fn generate_show_view(&self) -> String {
        let model = &self.config.model_name;
        let model_lower = model.to_lowercase();
        
        let fields: Vec<String> = self.config.fields
            .iter()
            .filter(|f| f.in_show)
            .map(|f| format!(
                r#"            <tr>
                <th>{}</th>
                <td>{{{{item.{}}}}}</td>
            </tr>"#,
                f.label, f.name
            ))
            .collect();
        
        format!(
            r#"{{{{#extend "layouts/app"}}}}
{{{{#content "content"}}}}
<div class="container">
    <div class="card">
        <div class="flex-between mb-2">
            <h1>{} Details</h1>
            <div>
                <a href="/admin/{}/{{{{item.id}}}}/edit" class="btn btn-primary btn-sm">Edit</a>
                <a href="/admin/{}" class="btn btn-secondary btn-sm">Back</a>
            </div>
        </div>
        
        <table class="table">
            {}
        </table>
    </div>
</div>
{{{{/content}}}}
{{{{/extend}}}}"#,
            model,
            model_lower,
            model_lower,
            fields.join("\n"),
        )
    }
    
    /// Generate all files
    pub fn generate_all(&self) -> GeneratedFiles {
        GeneratedFiles {
            controller: self.generate_controller(),
            list_view: self.generate_list_view(),
            form_view: self.generate_form_view(),
            show_view: self.generate_show_view(),
        }
    }
    
    /// Get the configuration
    pub fn config(&self) -> &ScaffoldConfig {
        &self.config
    }
}

/// Generated files
#[derive(Debug, Clone)]
pub struct GeneratedFiles {
    pub controller: String,
    pub list_view: String,
    pub form_view: String,
    pub show_view: String,
}

/// Scaffold builder for fluent configuration
pub struct ScaffoldBuilder {
    config: ScaffoldConfig,
}

impl ScaffoldBuilder {
    pub fn new(model_name: &str) -> Self {
        Self {
            config: ScaffoldConfig {
                model_name: model_name.to_string(),
                table_name: format!("{}s", model_name.to_lowercase()),
                ..Default::default()
            },
        }
    }
    
    pub fn table(mut self, table: &str) -> Self {
        self.config.table_name = table.to_string();
        self
    }
    
    pub fn field(mut self, field: ScaffoldField) -> Self {
        self.config.fields.push(field);
        self
    }
    
    pub fn per_page(mut self, per_page: u32) -> Self {
        self.config.per_page = per_page;
        self
    }
    
    pub fn searchable(mut self, searchable: bool) -> Self {
        self.config.searchable = searchable;
        self
    }
    
    pub fn sortable(mut self, sortable: bool) -> Self {
        self.config.sortable = sortable;
        self
    }
    
    pub fn build(self) -> AdminGenerator {
        AdminGenerator::new(self.config)
    }
}

/// Field builder helper
pub struct FieldBuilder {
    field: ScaffoldField,
}

impl FieldBuilder {
    pub fn new(name: &str, field_type: FieldType) -> Self {
        Self {
            field: ScaffoldField {
                name: name.to_string(),
                field_type,
                label: name.to_string(),
                required: false,
                searchable: false,
                sortable: false,
                in_list: true,
                in_form: true,
                in_show: true,
                validation: vec![],
                default_value: None,
                options: None,
            },
        }
    }
    
    pub fn label(mut self, label: &str) -> Self {
        self.field.label = label.to_string();
        self
    }
    
    pub fn required(mut self) -> Self {
        self.field.required = true;
        self.field.validation.push(ValidationRule {
            rule: "required".to_string(),
            message: format!("{} is required", self.field.label),
        });
        self
    }
    
    pub fn searchable(mut self) -> Self {
        self.field.searchable = true;
        self
    }
    
    pub fn sortable(mut self) -> Self {
        self.field.sortable = true;
        self
    }
    
    pub fn in_list(mut self, show: bool) -> Self {
        self.field.in_list = show;
        self
    }
    
    pub fn in_form(mut self, show: bool) -> Self {
        self.field.in_form = show;
        self
    }
    
    pub fn validation(mut self, rule: &str, message: &str) -> Self {
        self.field.validation.push(ValidationRule {
            rule: rule.to_string(),
            message: message.to_string(),
        });
        self
    }
    
    pub fn options(mut self, opts: Vec<(String, String)>) -> Self {
        self.field.options = Some(opts);
        self
    }
    
    pub fn build(self) -> ScaffoldField {
        self.field
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_scaffold_generation() {
        let generator = ScaffoldBuilder::new("Post")
            .table("posts")
            .field(
                FieldBuilder::new("title", FieldType::String)
                    .label("Title")
                    .required()
                    .searchable()
                    .build()
            )
            .field(
                FieldBuilder::new("content", FieldType::Textarea)
                    .label("Content")
                    .required()
                    .in_list(false)
                    .build()
            )
            .field(
                FieldBuilder::new("status", FieldType::Select)
                    .label("Status")
                    .options(vec![
                        ("draft".to_string(), "Draft".to_string()),
                        ("published".to_string(), "Published".to_string()),
                    ])
                    .build()
            )
            .build();
        
        let files = generator.generate_all();
        
        assert!(files.controller.contains("PostController"));
        assert!(files.controller.contains("register_routes"));
        assert!(files.list_view.contains("Posts"));
        assert!(files.form_view.contains("New Post"));
        assert!(files.show_view.contains("Post Details"));
    }
    
    #[test]
    fn test_field_builder() {
        let field = FieldBuilder::new("email", FieldType::Email)
            .label("Email Address")
            .required()
            .validation("email", "Must be a valid email")
            .build();
        
        assert_eq!(field.name, "email");
        assert_eq!(field.label, "Email Address");
        assert!(field.required);
        assert_eq!(field.validation.len(), 2);
    }
}
